version: '3.8'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/code
    ports:
      - "${NEXT_PUBLIC_SERVER_PORT}:${NEXT_PUBLIC_SERVER_PORT}"

  frontend:
    build: ./frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      NEXT_PUBLIC_SERVER_HOST: ${NEXT_PUBLIC_SERVER_HOST}
      NEXT_PUBLIC_SERVER_PORT: ${NEXT_PUBLIC_SERVER_PORT}

volumes:
  postgres_data:
